source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'TransactionAnimations_Example', :exclusive => true do
  pod "TransactionAnimations", :path => "../"
end

target 'TransactionAnimations_Tests', :exclusive => true do
  pod "TransactionAnimations", :path => "../"

  
end
